apiVersion: core.pingcap.com/v1alpha1
kind: TiDBGroup
metadata:
  name: tidb
  labels:
    pingcap.com/group: tidb
    pingcap.com/component: tidb
    pingcap.com/cluster: basic
spec:
  cluster:
    name: basic
  version: v8.1.0
  replicas: 2
  service:
    type: ClusterIP
  template:
    metadata:
      annotations:
        author: pingcap
    spec:
      resources:
        cpu: "1"
        memory: 2Gi
      config: |
        [log]
        level = "debug"
