apiVersion: core.pingcap.com/v1alpha1
kind: TiFlashGroup
metadata:
  name: tiflash
  labels:
    pingcap.com/group: tiflash
    pingcap.com/component: tiflash
    pingcap.com/cluster: basic
spec:
  cluster:
    name: basic
  version: v8.1.0
  replicas: 1
  template:
    metadata:
      annotations:
        author: pingcap
    spec:
      resources:
        cpu: "4"
        memory: 8Gi
      config: |
        mark_cache_size = 1073741824
      proxyConfig: ""
      volumes:
      - name: data
        # to compatible with the cluster managed by TiDB Operator v1
        # this path should often be /data0
        path: /data0
        for:
        - type: data
        storage: 100Gi
